In [2]:
import pandas as pd
df = pd.read_csv('citrus.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10000 non-null  object 
 1   diameter  10000 non-null  float64
 2   weight    10000 non-null  float64
 3   red       10000 non-null  int64  
 4   green     10000 non-null  int64  
 5   blue      10000 non-null  int64  
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB


In [5]:
df.head(10000)

name  diameter  weight  red  green  blue
0         orange      2.96   86.76  172     85     2
1         orange      3.91   88.05  166     78     3
2         orange      4.42   95.17  156     81     2
3         orange      4.47   95.60  163     81     4
4         orange      4.48   95.76  161     72     9
...          ...       ...     ...  ...    ...   ...
9995  grapefruit     15.35  253.89  149     77    20
9996  grapefruit     15.41  254.67  148     68     7
9997  grapefruit     15.59  256.50  168     82    20
9998  grapefruit     15.92  260.14  142     72    11
9999  grapefruit     16.45  261.51  152     74     2

[10000 rows x 6 columns]

In [7]:
df.name[df.name == 'orange'] = 0
df.name[df.name == 'grapefruit'] = 1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [10]:
dataset = df.values

In [11]:
dataset

array([[0, 2.96, 86.76, 172, 85, 2],
       [0, 3.91, 88.05, 166, 78, 3],
       [0, 4.42, 95.17, 156, 81, 2],
       ...,
       [1, 15.59, 256.5, 168, 82, 20],
       [1, 15.92, 260.14, 142, 72, 11],
       [1, 16.45, 261.51, 152, 74, 2]], dtype=object)

In [13]:
# pilih 4 kolom terakhir sebagai atribut
X = dataset[:,1:6]
# bilangan sebelum koma untuk memilih baris pada dataframe
# bilangan setelah koma untuk memilih kolom pada dataframe

In [14]:
X

array([[2.96, 86.76, 172, 85, 2],
       [3.91, 88.05, 166, 78, 3],
       [4.42, 95.17, 156, 81, 2],
       ...,
       [15.59, 256.5, 168, 82, 20],
       [15.92, 260.14, 142, 72, 11],
       [16.45, 261.51, 152, 74, 2]], dtype=object)

In [16]:
y = dataset[:,0]
y

array([0, 0, 0, ..., 1, 1, 1], dtype=object)

In [17]:
# Normalization
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)
X_scale

array([[0.        , 0.        , 0.74025974, 0.63529412, 0.        ],
       [0.07042254, 0.00738197, 0.66233766, 0.55294118, 0.01851852],
       [0.10822832, 0.04812589, 0.53246753, 0.58823529, 0.        ],
       ...,
       [0.93624907, 0.97133047, 0.68831169, 0.6       , 0.33333333],
       [0.96071164, 0.99216023, 0.35064935, 0.48235294, 0.16666667],
       [1.        , 1.        , 0.48051948, 0.50588235, 0.        ]])

In [19]:
# pisahkan data training dan testing
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_scale, y, test_size=0.3)

In [20]:
import numpy as np
 
Y_train = Y_train.astype(np.float32)
Y_test = Y_test.astype(np.float32)

In [21]:
from keras.models import Sequential
from keras.layers import Dense

In [23]:
model = Sequential([    
                    Dense(32, activation='relu', input_shape=(5,)),    
                    Dense(32, activation='relu'),    
                    Dense(1, activation='sigmoid'),])

In [24]:
model.compile(optimizer='sgd',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [25]:
model.fit(X_train, Y_train, epochs=100)

Epoch 1/100
219/219 [==============================] - 13s 827us/step - loss: 0.6848 - accuracy: 0.5708
Epoch 2/100
219/219 [==============================] - 0s 904us/step - loss: 0.6307 - accuracy: 0.9021
Epoch 3/100
219/219 [==============================] - 0s 845us/step - loss: 0.5789 - accuracy: 0.9130
Epoch 4/100
219/219 [==============================] - 0s 841us/step - loss: 0.5092 - accuracy: 0.9226
Epoch 5/100
219/219 [==============================] - 0s 842us/step - loss: 0.4186 - accuracy: 0.9235
Epoch 6/100
219/219 [==============================] - 0s 857us/step - loss: 0.3354 - accuracy: 0.9242
Epoch 7/100
219/219 [==============================] - 0s 821us/step - loss: 0.2756 - accuracy: 0.9287
Epoch 8/100
219/219 [==============================] - 0s 812us/step - loss: 0.2371 - accuracy: 0.9267
Epoch 9/100
219/219 [==============================] - 0s 847us/step - loss: 0.2142 - accuracy: 0.9272
Epoch 10/100
219/219 [==============================] - 0s 823us/step - 

In [26]:
model.evaluate(X_test, Y_test)
# elemen pertama adalah loss dan elemen kedua adalah akurasi

94/94 [==============================] - 0s 807us/step - loss: 0.1827 - accuracy: 0.9240


[0.18272510170936584, 0.9240000247955322]